version: '3.7'

services:
  orders:
      build:
        context: ./services/pedidos
        dockerfile: Dockerfile-dev
      volumes:
        - './services/pedidos:/usr/src/app'
      ports:
        - 5001:5000
      environment:
        - FLASK_ENV=development
        - APP_SETTINGS=project.config.DevelopmentConfig
        - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev  # nuevo
        - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test  # nuevo
      depends_on:  # nuevo
        - users-db

  users-db:  # nuevo
    build:
      context: ./services/pedidos/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres